### ISSUE TITLE
Journal Functionality

### ISSUE THREAD

**Issue by simonzeiger** [cs130-w21/2#2]
## Epic Description
This feature allows users to write journal entries about their trips that can be tied to specific locations.  Users will be able to click on specific locations from their trip to view the notes associated with these locations.  It will also allow users to sort their entries by the date that they were created.

## Bulletpoints
- Create Note 
- Associate Note with location along trip 
- Sort Notes by location or date 

## User Stories
- [x] Note Page #33 
- [x] Create Note #6 
- [x] Store Notes in Database #53 
- [x] Note control (edit, delete) #56 
- [x] Open Correct Notes #62
