### ISSUE TITLE
Trip View Functionality

### ISSUE THREAD

**Issue by simonzeiger** [cs130-w21/2#3]
## Epic Description
This feature allows the user to view and edit trip.

## Bullet Points

 Search for location
 Add locations to trip 
 Include Google places info with locations 
 View and alter map 
 Navigate to notes
 Navigate to Spotify 
 Navigate to Images 

## Stories
- [x] Search for location #9 
- [x] Add locations to trip #10 
- [x] Include Google places info with locations #11 
- [x] View map #29
- [x] Alter map #21
- [x] Navigate to notes #22
- [x] Navigate to Spotify #23
- [x] Navigate to Images #25
- [x] View list of locations #36
