### ISSUE TITLE
Note Control

### ISSUE THREAD

**Issue by jasonpanelli** [cs130-w21/2#56]
## User Story
As a user, I would like to be able to edit and delete notes so that I can organize my journals.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [x] Add page to read note #68 
- [x] Add button to note reading page for note editing #75 
- [x] Create editing dialog #66 
- [ ] Populate the text fields of the edit dialog with the note
- [x] Add delete button to remove note from list of notes #71
