### ISSUE TITLE
Create Note

### ISSUE THREAD

**Issue by DrewCaylor** [cs130-w21/2#6]
## User Story
As a user, I would like to be able to create a note so that I can record details of my trip.

## Detailed Description
User can click 'create new note' to make a journal entry about their trip.  This will bring up a window where they can write and submit the entry.

## Acceptance Criteria
- [x] - Skeleton code for Note activity
- [x] - Notes will appear in a list on the notes page #39
- [x] - A creation button will create a new note #38
- [x] - When the creation button is pressed, the user should be able to initially add some text to the note #54 
- [x] - When the user finishes adding the note, the note should appear in the list of notes in the Note activity
- [x] - The note should be added to the DB #55
